---


  #Sample package
- name: Download binary pakage
  get_url:
    url: https://osdn.net/projects/pal/downloads/17479/helloworld.war
    dest: /etc/foo.conf
    mode: '0440'

- name: Setup tomcat service
  template:
    src: "tomcat.service.j2"
    dest: "/lib/systemd/system/tomcat.service"

